const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync('admin/story-studio/index.html','utf8');new vm.Script(html.match(/<script>\s*([\s\S]*?)<\/script>/)[1]);
const nodes=new Proxy({}, {get:(o,k)=>o[k]??={value:'',style:{},attrs:{},setAttribute(k,v){this.attrs[k]=v},querySelectorAll(){return []}}});
const c={$:id=>nodes[id],editor:{setContent(v){c.content=v},getContent(){return '<p>My story</p>'}},draftId:'current',photos:[],cover:'',document:{querySelector(){return {textContent:'@media(max-width:640px){.photo{width:100%}}'}}},figure(){return ''},save:async()=>c.steps.push('save'),request:async()=>{c.steps.push('create');return {data:{id:'new'}}},applyDraft(){c.steps.push('apply')},refreshDrafts:async()=>c.steps.push('refresh'),steps:[]};vm.createContext(c);
for(const prefix of ['function esc','function draftStatus','function filteredDrafts','function storyPreview','function snapshot','function previewDocument','function previewMode','async function createDraft'])vm.runInContext(html.split('\n').find(l=>l.startsWith(prefix)),c);
vm.runInContext(html.slice(html.indexOf('const STORY_TEMPLATES='),html.indexOf('async function createDraft(')),c);
const drafts=[{title:'Trip',published:null},{title:'Trip live',published:{slug:'trip'}},{title:'Quiet',published:{active:false}}];assert.equal(c.filteredDrafts(drafts,'published','TRIP').length,1);assert.equal(c.filteredDrafts(drafts,'draft','').length,1);assert.equal(c.filteredDrafts(drafts,'unpublished','').length,1);
c.previewMode(true);assert.equal(nodes['preview-frame'].style.width,'390px');assert.equal(nodes['preview-phone'].attrs['aria-pressed'],true);c.previewMode(false);assert.equal(nodes['preview-frame'].style.width,'100%');nodes.title.value='<unsafe>';const doc=c.previewDocument();assert(doc.includes('&lt;unsafe&gt;'));assert(doc.includes('@media(max-width:640px)'));assert(html.includes('sandbox="allow-same-origin"'));assert(!html.includes('sandbox="allow-same-origin allow-scripts"'));
(async()=>{await c.createDraft('trip');assert.deepEqual(c.steps,['save','create','apply','save','refresh']);assert(c.content.includes('Where we went'));c.steps=[];c.save=async()=>{throw Error('Save failed')};await assert.rejects(c.createDraft('photos'),/Save failed/);assert.deepEqual(c.steps,[]);console.log('Phone viewport, preview escaping, template save sequencing and dashboard filters pass.');})().catch(e=>{console.error(e);process.exitCode=1});
