// SPDX-License-Identifier: GPL-2.0-or-later
// Copyright (c) 2026 Clint and Liz DuBois. See LICENSE and NOTICE.md.
const fs=require('fs'),vm=require('vm'),assert=require('assert');const html=fs.readFileSync('admin/story-studio/index.html','utf8');
const nodes=new Proxy({}, {get:(o,k)=>o[k]??={value:'',style:{},showModal(){},close(){},setAttribute(){}}});
let confirmRestore=false;const calls=[];const current={title:'A story',date:'2026-10-07',html:'<p>Old</p>',updated:'2026-10-07T12:00:00Z'};
const c={$:id=>nodes[id],draftId:'draft',etag:'v1',save:async()=>calls.push('save'),request:async(path,options)=>{calls.push(options?.method==='POST'?'restore':'get');return path.includes('?')||options?{data:current,etag:'v2'}:{data:{versions:[{id:'version',title:'Old',saved:current.updated}]}}},applyDraft(){calls.push('apply')},refreshDrafts:async()=>calls.push('refresh'),toast(){},confirm:()=>confirmRestore,storyPreview:()=>'<p>Preview</p>',photos:[{id:'external',src:'https://legacy.example/media/a.jpg'},{id:'local',src:'/api/story-media/draft/photo'}],editor:{getContent:()=>''},initial:'',location:{origin:'https://studio.example'},URL,DOMParser:class{parseFromString(){return {querySelectorAll(){return ['https://legacy.example/media/a.jpg','https://studio.example/api/story-media/draft/photo/thumbnail'].map(src=>({getAttribute:()=>src}))}}}}};vm.createContext(c);
for(const prefix of ['function esc','function storyPhotoCounts'])vm.runInContext(html.split('\n').find(l=>l.startsWith(prefix)),c);
vm.runInContext(html.slice(html.indexOf("let selectedVersion="),html.indexOf("$('export').onclick=")),c);
(async()=>{const counts=c.storyPhotoCounts();assert.equal(counts.get('external'),1);assert.equal(counts.get('local'),1);await nodes.history.onclick();assert.deepEqual(calls,['save','get']);await nodes['history-list'].onclick({target:{closest:()=>({dataset:{version:'version'}})}});assert.equal(nodes['restore-version'].disabled,false);calls.length=0;await nodes['restore-version'].onclick();assert.equal(calls.length,0);confirmRestore=true;await nodes['restore-version'].onclick();assert.deepEqual(calls,['save','restore','apply','refresh']);console.log('History review/confirmation, save-before-restore and imported photo usage tracking pass.');})().catch(e=>{console.error(e);process.exitCode=1});
